### ISSUE TITLE
Video files with special characters can't be edited

### ISSUE THREAD

**Issue by pizzadude** [keshavbhatt/plumber#2]
Video files with special characters can't be edited.
Example filename: 'Blend-S - Opening | Bon Appétit♡S - ZRrauyTlT6U.mkv'

It could be either the '♡' or the " | " in the filename, not sure.

When trying to save the edit, this is displayed
 "An error occured while processing your request "

**Comment by keshavbhatt** [comment]
i will git it a try. thanks for reporting.

**Comment by keshavbhatt** [comment]
i tried a video with similar title and it works fine here.

**Comment by pizzadude** [comment]
Try with the exact same title.

**Comment by keshavbhatt** [comment]
You using the snap install or what ?

**Comment by keshavbhatt** [comment]
Actually the video [Blend-S - Opening | Bon Appétit♡S ](https://www.youtube.com/watch?v=ZRrauyTlT6U) is not available in my country. 

So i tried [this video](https://www.youtube.com/watch?v=7K5St3roHek) with similar title and chars in it, Plumber gave me no error.

Plumber removed unsupported chars automatically and turned the title to this:
(Blend-S _ Buon Appetito♡S _ぼなぺてぃーと♡S _ All staff ver. (Blend-S Episode 12 Ending Theme)-7K5St3roHek.mkv)

**Comment by pizzadude** [comment]
I mean if I use a local video file.

**Comment by pizzadude** [comment]
I'm using snap install on Fedora 32. I didn't use the youtube feature, I just selected a local video file.

**Comment by pizzadude** [comment]
It only worked if I renamed the file.

**Comment by keshavbhatt** [comment]
yes, i got it. its a bug as right now plumber wont sanitize title of local media. 
Fix coming soon. thanks for reporting.
