### ISSUE TITLE
Media probe engine not present or not updated.

### ISSUE THREAD

**Issue by adder46** [keshavbhatt/plumber#4]
I tried to use the app, I installed it using `snap`, however I'm getting this error.
When I click to update the engine, it just hangs, with the error: 

```
Socket operation timed out
```

**Comment by keshavbhatt** [comment]
are you able to access ktechpit.com in your browser ?

**Comment by adder46** [comment]
> are you able to access ktechpit.com in your browser ?

Yes.

**Comment by keshavbhatt** [comment]
Can you retry downloading the engine? It must be a temporary issue with my host.

**Comment by adder46** [comment]
Should be working now.
