### ISSUE TITLE
App will not install

### ISSUE THREAD

**Issue by Sauron0** [keshavbhatt/plumber#9]
I installed this app on Fedora 33 successfully about 5 months ago.
Now I'm trying to install it on another machine running Fedora 33.  The application will not install.  The install stalls here:
![Screenshot_20210915_124804-1](https://user-images.githubusercontent.com/46358998/133944765-1e76c72b-d11c-4e3f-991a-7b20adbeb0fb.png)

Nothing happens after this.

**Comment by keshavbhatt** [comment]
wait for snapd to download qt513 content snap that contain the required runtime of this app.
